### ISSUE TITLE
老哥可以加Q交流下吗 同款

### ISSUE THREAD

**Issue by fatFire** [YuechenW/Hackintosh-x1c5-10.14.6#1]
老哥你现在用的config是哪一个? 多手势完善的那个吗

**Comment by fatFire** [comment]
我现在是10.15.4 直接替换你的efi不成功

**Comment by fatFire** [comment]
我q 919615766 看到麻烦加下 谢谢啦

**Comment by YuechenW** [comment]
config用默认的那个就是最新编辑的，用不了可以用其他备份的旧版本试试
10.15没有测试过，而且应该也不会适配了
需要注意的是我的u是 i5 6200U，如果你的不是，需要重新打缓冲帧
最近有点忙，就先不加q了。qwq

**Comment by fatFire** [comment]
> config用默认的那个就是最新编辑的，用不了可以用其他备份的旧版本试试
> 10.15没有测试过，而且应该也不会适配了
> 需要注意的是我的u是 i5 6200U，如果你的不是，需要重新打缓冲帧
> 最近有点忙，就先不加q了。qwq

谢谢大佬，我是和你同款 i5-6200，找了全网只有你这一个，我现在换成了14.6完美

**Comment by YuechenW** [comment]
好的 不用谢
