### ISSUE TITLE
是否屏蔽了网卡

### ISSUE THREAD

**Issue by fatFire** [YuechenW/Hackintosh-x1c5-10.14.6#2]
大佬您好, 我是用的原装 intel的8265网卡, 用论坛大佬的intel网卡驱动没有反应, 是不是efi里屏蔽了网卡?

**Comment by fatFire** [comment]
http://bbs.pcbeta.com/viewthread-1862698-1-1.html  这是远景论坛intel无线网卡教程

**Comment by YuechenW** [comment]
应该没有屏蔽，intel的网卡我还没试过。。加qq吧

**Comment by YuechenW** [comment]
Q:1215823863
